var searchData=
[
  ['base_20and_20cuda_20graph_20capture_0',['base and cuda graph capture',['../stage_lorenzo_quant.html#autotoc_md129',1,'Value base and CUDA Graph capture'],['../stage_quantizer.html#autotoc_md163',1,'Value base and CUDA Graph capture']]],
  ['based_20pipeline_20abs_20error_1',['Lorenzo-based pipeline (ABS error)',['../config_file_overview.html#autotoc_md223',1,'']]],
  ['be_20enabled_2',['1. Zigzag encoding must be enabled',['../stage_quantizer.html#autotoc_md159',1,'']]],
  ['before_20finalize_3',['Configuration (before finalize())',['../api_reference.html#autotoc_md241',1,'']]],
  ['benchmarking_4',['Benchmarking',['../cli_overview.html#autotoc_md230',1,'']]],
  ['best_20ratio_20on_20smooth_20data_5',['Lorenzo + RZE (best ratio on smooth data)',['../libpressio_python.html#autotoc_md392',1,'']]],
  ['bidirectional_20estimateoutputsizes_6',['Non-size-preserving stages: bidirectional estimateOutputSizes',['../how_to_add_a_stage.html#autotoc_md296',1,'']]],
  ['binary_20output_7',['Binary Output',['../building_from_source.html#autotoc_md34',1,'']]],
  ['bindings_8',['LibPressio Python Bindings',['../libpressio_python.html',1,'']]],
  ['bit_20width_9',['Manual bit-width',['../stage_bitpack.html#autotoc_md53',1,'']]],
  ['bitpack_10',['Bitpack',['../config_file_overview.html#autotoc_md219',1,'']]],
  ['bitpack_5fstage_2eh_11',['bitpack_stage.h',['../bitpack__stage_8h.html',1,'']]],
  ['bitpacking_12',['Bitpacking',['../libpressio_python.html#autotoc_md383',1,'']]],
  ['bitpackstage_13',['bitpackstage',['../stage_bitpack.html',1,'BitpackStage'],['../classfz_1_1BitpackStage.html',1,'fz::BitpackStage&lt; T &gt;']]],
  ['bitshuffle_14',['bitshuffle',['../libpressio_python.html#autotoc_md384',1,'Bitshuffle'],['../config_file_overview.html#autotoc_md212',1,'Bitshuffle'],['../libpressio_python.html#autotoc_md393',1,'Lorenzo + Bitshuffle']]],
  ['bitshuffle_5fstage_2eh_15',['bitshuffle_stage.h',['../bitshuffle__stage_8h.html',1,'']]],
  ['bitshufflestage_16',['bitshufflestage',['../classfz_1_1BitshuffleStage.html',1,'fz::BitshuffleStage'],['../stage_bitshuffle.html',1,'BitshuffleStage']]],
  ['bklen_20tt_17',['Setting &lt;tt&gt;bklen&lt;/tt&gt;',['../stage_huffman.html#autotoc_md86',1,'']]],
  ['bound_20modes_18',['bound modes',['../stage_quantizer.html#autotoc_md155',1,'Error bound modes'],['../libpressio_python.html#autotoc_md374',1,'Error bound modes'],['../stage_lorenzo_quant.html#autotoc_md125',1,'Error bound modes']]],
  ['boundary_19',['Public API boundary',['../api_reference.html#autotoc_md264',1,'']]],
  ['branched_20pipelines_20via_20toml_20config_20',['Branched pipelines via TOML config',['../cli_overview.html#autotoc_md229',1,'']]],
  ['buffer_21',['FZMBufferEntry (256 bytes, one per buffer)',['../fzm_format.html#autotoc_md328',1,'']]],
  ['buffer_20layout_22',['Internal buffer layout',['../stage_huffman.html#autotoc_md97',1,'']]],
  ['buffer_20no_20internal_20allocation_23',['Caller-allocated buffer (no internal allocation)',['../api_reference.html#autotoc_md252',1,'']]],
  ['bufferinfo_24',['BufferInfo',['../structfz_1_1BufferInfo.html',1,'fz']]],
  ['build_25',['Quick Build',['../building_from_source.html#autotoc_md26',1,'']]],
  ['build_20examples_26',['Common Build Examples',['../building_from_source.html#autotoc_md32',1,'']]],
  ['build_20failures_20in_20ci_27',['Build Failures in CI',['../md_docs_2docker.html#autotoc_md355',1,'']]],
  ['build_20with_20all_20targets_28',['Full Build with All Targets',['../md_docs_2docker.html#autotoc_md347',1,'']]],
  ['builder_20optional_29',['Step 8 — Register in the CLI dynamic builder *(optional)*',['../how_to_add_a_stage.html#autotoc_md314',1,'']]],
  ['buildheader_30',['buildHeader',['../classfz_1_1Pipeline.html#ad2e45c30aaa4e4b5d4052c34e5228cf4',1,'fz::Pipeline']]],
  ['building_20from_20source_31',['building from source',['../index.html#autotoc_md5',1,'Building from Source'],['../building_from_source.html',1,'Building from Source']]],
  ['building_20fzgpumodules_20itself_32',['Local Development (Building FZGPUModules Itself)',['../md_docs_2docker.html#autotoc_md344',1,'']]],
  ['building_20the_20docker_20image_33',['Building the Docker Image',['../md_docs_2docker.html#autotoc_md339',1,'']]],
  ['building_20the_20graph_34',['Building the Graph',['../api_reference.html#autotoc_md243',1,'']]],
  ['byte_5foffset_35',['byte_offset',['../structfz_1_1FZMBufferEntry.html#ae55a4cbbafb6d33533e3bc62522167e4',1,'fz::FZMBufferEntry']]],
  ['bytes_36',['FZMHeaderCore (80 bytes)',['../fzm_format.html#autotoc_md324',1,'']]],
  ['bytes_20one_20per_20buffer_37',['FZMBufferEntry (256 bytes, one per buffer)',['../fzm_format.html#autotoc_md328',1,'']]],
  ['bytes_20one_20per_20stage_38',['FZMStageInfo (256 bytes, one per stage)',['../fzm_format.html#autotoc_md326',1,'']]]
];
