var searchData=
[
  ['launchlorenzoinversekernel2d_0',['launchLorenzoInverseKernel2D',['../lorenzo__quant_8h.html#a707637dd5443a9c8b03dd226287b4ac8',1,'fz']]],
  ['launchlorenzoinversekernel3d_1',['launchLorenzoInverseKernel3D',['../lorenzo__quant_8h.html#a218aaf82a9687bb616b4047d33837d08',1,'fz']]],
  ['launchlorenzokernel2d_2',['launchLorenzoKernel2D',['../lorenzo__quant_8h.html#a8e8f5e059498e45150cdcc911048ccf0',1,'fz']]],
  ['launchlorenzokernel3d_3',['launchLorenzoKernel3D',['../lorenzo__quant_8h.html#a556c53eeabb64269c1cdc96a79a19d90',1,'fz']]],
  ['layer_20model_4',['Layer Model',['../architecture.html#autotoc_md271',1,'']]],
  ['layout_5',['layout',['../fzm_format.html#autotoc_md322',1,'File Layout'],['../stage_huffman.html#autotoc_md97',1,'Internal buffer layout']]],
  ['layout_20forward_20output_6',['layout forward output',['../stage_rze.html#autotoc_md189',1,'Stream layout (forward output)'],['../stage_rle.html#autotoc_md179',1,'Stream layout (forward output)']]],
  ['length_20encoding_20rle_7',['Run-Length Encoding (RLE)',['../libpressio_python.html#autotoc_md382',1,'']]],
  ['level_8',['level',['../structfz_1_1StageTimingResult.html#ac4f66e37f3a9c2bbc31a58c2bd16c38e',1,'fz::StageTimingResult::level'],['../structfz_1_1LevelTimingResult.html#ad8ca957fe0daa5b02aa7ff6c4bef3d8b',1,'fz::LevelTimingResult::level']]],
  ['level_20settings_9',['[pipeline] &amp;ndash; pipeline-level settings',['../config_file_overview.html#autotoc_md207',1,'']]],
  ['levels_10',['levels',['../structfz_1_1PipelinePerfResult.html#aef5775672ffc0606b57d63eace8afd8d',1,'fz::PipelinePerfResult']]],
  ['leveltimingresult_11',['LevelTimingResult',['../structfz_1_1LevelTimingResult.html',1,'fz']]],
  ['libpressio_20python_20bindings_12',['LibPressio Python Bindings',['../libpressio_python.html',1,'']]],
  ['libpressio_20source_20fork_13',['Point spack at the libpressio source fork',['../libpressio_python.html#autotoc_md363',1,'']]],
  ['library_14',['library',['../fzm_format.html#autotoc_md334',1,'Reading a File Without the Library'],['../md_docs_2docker.html#autotoc_md340',1,'Using the Pre-Installed Library']]],
  ['lifecycle_20at_20a_20glance_15',['Lifecycle at a Glance',['../api_reference.html#autotoc_md233',1,'']]],
  ['limitations_16',['limitations',['../config_file_overview.html#autotoc_md226',1,'Limitations'],['../stage_huffman.html#huffman-limitations',1,'Limitations']]],
  ['line_20interface_17',['Command Line Interface',['../cli_overview.html',1,'']]],
  ['linear_20pipelines_18',['Dynamic linear pipelines',['../cli_overview.html#autotoc_md227',1,'']]],
  ['loadconfig_19',['loadConfig',['../classfz_1_1Pipeline.html#a4c90bfac014f227be65b5683cb27c92f',1,'fz::Pipeline']]],
  ['loader_20',['Step 7 — Register in the TOML config loader',['../how_to_add_a_stage.html#autotoc_md312',1,'']]],
  ['local_20development_20building_20fzgpumodules_20itself_21',['Local Development (Building FZGPUModules Itself)',['../md_docs_2docker.html#autotoc_md344',1,'']]],
  ['location_22',['Step 1 — Choose a location',['../how_to_add_a_stage.html#autotoc_md291',1,'']]],
  ['locations_23',['Shared output locations',['../how_to_add_a_stage.html#autotoc_md302',1,'']]],
  ['log_24',['log',['../classfz_1_1Logger.html#a2fc91d922533e5e340a0c9f3df20e392',1,'fz::Logger']]],
  ['log_2eh_25',['log.h',['../log_8h.html',1,'']]],
  ['logger_26',['Logger',['../classfz_1_1Logger.html',1,'fz']]],
  ['logging_27',['Logging',['../architecture.html#autotoc_md285',1,'']]],
  ['loglevel_28',['LogLevel',['../log_8h.html#aed168b7f4825b1f0f5b87507949fa161',1,'fz']]],
  ['lorenzo_29',['Lossless Integer Lorenzo',['../libpressio_python.html#autotoc_md395',1,'']]],
  ['lorenzo_20based_20pipeline_20abs_20error_30',['Lorenzo-based pipeline (ABS error)',['../config_file_overview.html#autotoc_md223',1,'']]],
  ['lorenzo_20bitshuffle_31',['Lorenzo + Bitshuffle',['../libpressio_python.html#autotoc_md393',1,'']]],
  ['lorenzo_20huffman_32',['cuSZ-style Lorenzo + Huffman',['../stage_huffman.html#autotoc_md90',1,'']]],
  ['lorenzo_20predictor_20quantizer_33',['Lorenzo Predictor + Quantizer',['../libpressio_python.html#autotoc_md378',1,'']]],
  ['lorenzo_20rle_20default_34',['Lorenzo + RLE (default)',['../libpressio_python.html#autotoc_md391',1,'']]],
  ['lorenzo_20rze_20best_20ratio_20on_20smooth_20data_35',['Lorenzo + RZE (best ratio on smooth data)',['../libpressio_python.html#autotoc_md392',1,'']]],
  ['lorenzo1d_20lorenzo2d_20lorenzo3d_36',['Lorenzo1D / Lorenzo2D / Lorenzo3D',['../config_file_overview.html#autotoc_md211',1,'']]],
  ['lorenzo2d_20lorenzo3d_37',['Lorenzo1D / Lorenzo2D / Lorenzo3D',['../config_file_overview.html#autotoc_md211',1,'']]],
  ['lorenzo3d_38',['Lorenzo1D / Lorenzo2D / Lorenzo3D',['../config_file_overview.html#autotoc_md211',1,'']]],
  ['lorenzo_5fquant_2eh_39',['lorenzo_quant.h',['../lorenzo__quant_8h.html',1,'']]],
  ['lorenzo_5fstage_2eh_40',['lorenzo_stage.h',['../lorenzo__stage_8h.html',1,'']]],
  ['lorenzoconfig_41',['LorenzoConfig',['../structfz_1_1LorenzoConfig.html',1,'fz']]],
  ['lorenzoquantconfig_42',['LorenzoQuantConfig',['../structfz_1_1LorenzoQuantConfig.html',1,'fz']]],
  ['lorenzoquantstage_43',['lorenzoquantstage',['../classfz_1_1LorenzoQuantStage.html',1,'fz::LorenzoQuantStage&lt; TInput, TCode &gt;'],['../stage_lorenzo_quant.html',1,'LorenzoQuantStage']]],
  ['lorenzostage_44',['lorenzostage',['../classfz_1_1LorenzoStage.html',1,'fz::LorenzoStage&lt; T &gt;'],['../stage_lorenzo.html',1,'LorenzoStage']]],
  ['lossless_20integer_20lorenzo_45',['Lossless Integer Lorenzo',['../libpressio_python.html#autotoc_md395',1,'']]]
];
