var searchData=
[
  ['base_20and_20cuda_20graph_20capture_0',['base and cuda graph capture',['../stage_lorenzo_quant.html#autotoc_md238',1,'Value base and CUDA Graph capture'],['../stage_quantizer.html#autotoc_md290',1,'Value base and CUDA Graph capture']]],
  ['based_20on_20prior_20work_1',['Step 8b — Attribution *(required when based on prior work)*',['../how_to_add_a_stage.html#autotoc_md484',1,'']]],
  ['based_20pipeline_20abs_20error_2',['Lorenzo-based pipeline (ABS error)',['../config_file_overview.html#autotoc_md387',1,'']]],
  ['be_20enabled_3',['1. Zigzag encoding must be enabled',['../stage_quantizer.html#autotoc_md286',1,'']]],
  ['before_20finalize_4',['Configuration (before finalize())',['../api_reference.html#autotoc_md406',1,'']]],
  ['behaviour_5',['Radius auto-tune (default behaviour)',['../classfz_1_1GInterpStage.html#autotoc_md4',1,'']]],
  ['behaviour_20notes_6',['Behaviour notes',['../stage_merge.html#autotoc_md249',1,'']]],
  ['benchmarking_7',['Benchmarking',['../cli_overview.html#autotoc_md394',1,'']]],
  ['best_20ratio_20on_20smooth_20data_8',['Lorenzo + RZE (best ratio on smooth data)',['../libpressio_python.html#autotoc_md562',1,'']]],
  ['bidirectional_20estimateoutputsizes_9',['Non-size-preserving stages: bidirectional estimateOutputSizes',['../how_to_add_a_stage.html#autotoc_md464',1,'']]],
  ['binary_20output_10',['Binary Output',['../building_from_source.html#autotoc_md44',1,'']]],
  ['bindings_11',['LibPressio Python Bindings',['../libpressio_python.html',1,'']]],
  ['bit_20width_12',['Manual bit-width',['../stage_bitpack.html#autotoc_md122',1,'']]],
  ['bitpack_13',['Bitpack',['../config_file_overview.html#autotoc_md383',1,'']]],
  ['bitpack_5fstage_2eh_14',['bitpack_stage.h',['../bitpack__stage_8h.html',1,'']]],
  ['bitpacking_15',['Bitpacking',['../libpressio_python.html#autotoc_md553',1,'']]],
  ['bitpackstage_16',['bitpackstage',['../stage_bitpack.html',1,'BitpackStage'],['../classfz_1_1BitpackStage.html',1,'fz::BitpackStage&lt; T &gt;']]],
  ['bitplane_5frze_17',['BITPLANE_RZE',['../namespacefz.html#a91f5c5157c5ae2919b8c6875d805aa72aac87b796531121a439aabce779a9ce5a',1,'fz']]],
  ['bitplane_5frze_5fkernels_2eh_18',['bitplane_rze_kernels.h',['../bitplane__rze__kernels_8h.html',1,'']]],
  ['bitplane_5frze_5fstage_2eh_19',['bitplane_rze_stage.h',['../bitplane__rze__stage_8h.html',1,'']]],
  ['bitplanerzestage_20',['bitplanerzestage',['../stage_bitplane_rze.html',1,'BitplaneRZEStage'],['../classfz_1_1BitplaneRZEStage.html',1,'fz::BitplaneRZEStage']]],
  ['bitshuffle_21',['bitshuffle',['../config_file_overview.html#autotoc_md374',1,'Bitshuffle'],['../libpressio_python.html#autotoc_md554',1,'Bitshuffle'],['../libpressio_python.html#autotoc_md563',1,'Lorenzo + Bitshuffle']]],
  ['bitshuffle_5fstage_2eh_22',['bitshuffle_stage.h',['../bitshuffle__stage_8h.html',1,'']]],
  ['bitshufflestage_23',['bitshufflestage',['../classfz_1_1BitshuffleStage.html',1,'fz::BitshuffleStage'],['../stage_bitshuffle.html',1,'BitshuffleStage']]],
  ['bitshufflestage_20rzestage_24',['bitshufflestage rzestage',['../stage_bitplane_rze.html#autotoc_md129',1,'Relationship to BitshuffleStage + RZEStage'],['../classfz_1_1BitplaneRZEStage.html#autotoc_md0',1,'Relationship to BitshuffleStage + RZEStage']]],
  ['bklen_20tt_25',['Setting &lt;tt&gt;bklen&lt;/tt&gt;',['../stage_huffman.html#autotoc_md193',1,'']]],
  ['blob_26',['Typical pipeline (cuSZ-Hi cr-mode merged blob)',['../stage_merge.html#autotoc_md251',1,'']]],
  ['block_5fsize_27',['block_size',['../structfz_1_1LorenzoConfig.html#ae4b226b183467a5edde8b5aeb73e96d9',1,'fz::LorenzoConfig::block_size'],['../structfz_1_1AdaptiveBitpackConfig.html#ab67b8b5bce97de9fd4b01ab54eeac074',1,'fz::AdaptiveBitpackConfig::block_size']]],
  ['bound_20and_20limitations_28',['bound and limitations',['../stage_ginterp.html#autotoc_md173',1,'Error bound and limitations'],['../classfz_1_1GInterpStage.html#autotoc_md1',1,'Error bound and limitations']]],
  ['bound_20modes_29',['bound modes',['../stage_quantizer.html#autotoc_md282',1,'Error bound modes'],['../libpressio_python.html#autotoc_md544',1,'Error bound modes'],['../stage_lorenzo_quant.html#autotoc_md234',1,'Error bound modes']]],
  ['bound_20modes_20rel_20is_20not_20exact_20pfpl_20per_20element_30',['Error-bound modes (REL is NOT exact PFPL per-element)',['../classfz_1_1GInterpStage.html#autotoc_md2',1,'']]],
  ['boundary_31',['Public API boundary',['../api_reference.html#autotoc_md432',1,'']]],
  ['branched_20pipelines_20via_20toml_20config_32',['Branched pipelines via TOML config',['../cli_overview.html#autotoc_md393',1,'']]],
  ['buffer_33',['FZMBufferEntry (256 bytes, one per buffer)',['../fzm_format.html#autotoc_md498',1,'']]],
  ['buffer_20layout_34',['Internal buffer layout',['../stage_huffman.html#autotoc_md204',1,'']]],
  ['buffer_20no_20internal_20allocation_35',['Caller-allocated buffer (no internal allocation)',['../api_reference.html#autotoc_md417',1,'']]],
  ['bufferinfo_36',['BufferInfo',['../structfz_1_1BufferInfo.html',1,'fz']]],
  ['buffers_20device_20footprint_37',['buffers device footprint',['../stage_ans.html#autotoc_md109',1,'Scratch buffers / device footprint'],['../stage_adm.html#autotoc_md88',1,'Scratch buffers / device footprint']]],
  ['build_38',['Quick Build',['../building_from_source.html#autotoc_md36',1,'']]],
  ['build_20examples_39',['Common Build Examples',['../building_from_source.html#autotoc_md42',1,'']]],
  ['build_20failures_20in_20ci_40',['Build Failures in CI',['../md_docs_2docker.html#autotoc_md525',1,'']]],
  ['build_20with_20all_20targets_41',['Full Build with All Targets',['../md_docs_2docker.html#autotoc_md517',1,'']]],
  ['builder_20optional_42',['Step 8 — Register in the CLI dynamic builder *(optional)*',['../how_to_add_a_stage.html#autotoc_md482',1,'']]],
  ['buildheader_43',['buildHeader',['../classfz_1_1Pipeline.html#ad2e45c30aaa4e4b5d4052c34e5228cf4',1,'fz::Pipeline']]],
  ['building_20from_20source_44',['building from source',['../index.html#autotoc_md13',1,'Building from Source'],['../building_from_source.html',1,'Building from Source']]],
  ['building_20fzgpumodules_20itself_45',['Local Development (Building FZGPUModules Itself)',['../md_docs_2docker.html#autotoc_md514',1,'']]],
  ['building_20the_20docker_20image_46',['Building the Docker Image',['../md_docs_2docker.html#autotoc_md509',1,'']]],
  ['building_20the_20graph_47',['Building the Graph',['../api_reference.html#autotoc_md408',1,'']]],
  ['byte_20array_20input_48',['Standalone (byte array input)',['../stage_ans.html#autotoc_md101',1,'']]],
  ['byte_5foffset_49',['byte_offset',['../structfz_1_1FZMBufferEntry.html#ae55a4cbbafb6d33533e3bc62522167e4',1,'fz::FZMBufferEntry']]],
  ['bytes_50',['FZMHeaderCore (80 bytes)',['../fzm_format.html#autotoc_md494',1,'']]],
  ['bytes_20one_20per_20buffer_51',['FZMBufferEntry (256 bytes, one per buffer)',['../fzm_format.html#autotoc_md498',1,'']]],
  ['bytes_20one_20per_20stage_52',['FZMStageInfo (256 bytes, one per stage)',['../fzm_format.html#autotoc_md496',1,'']]]
];
