var searchData=
[
  ['c_20api_20usage_0',['C++ API Usage',['../index.html#autotoc_md6',1,'']]],
  ['calculatestatistics_1',['calculateStatistics',['../stat_8h.html#a1e378f0769aaa07fee908c8a2b52a370',1,'fz']]],
  ['caller_20allocated_20buffer_20no_20internal_20allocation_2',['Caller-allocated buffer (no internal allocation)',['../api_reference.html#autotoc_md252',1,'']]],
  ['caller_20allocated_20output_3',['Caller-Allocated Output',['../index.html#autotoc_md10',1,'']]],
  ['caller_20owned_20output_4',['caller owned output',['../api_reference.html#autotoc_md247',1,'Caller-owned output'],['../api_reference.html#autotoc_md251',1,'Caller-owned output']]],
  ['cannot_20find_20fzgpumodules_5',['find_package Cannot Find FZGPUModules',['../md_docs_2docker.html#autotoc_md354',1,'']]],
  ['capture_6',['capture',['../api_reference.html#autotoc_md258',1,'CUDA Graph Capture'],['../stage_lorenzo_quant.html#autotoc_md129',1,'Value base and CUDA Graph capture'],['../stage_quantizer.html#autotoc_md163',1,'Value base and CUDA Graph capture']]],
  ['capturegraph_7',['captureGraph',['../classfz_1_1Pipeline.html#ae6fcaa9d197469e28e520897a1a91a0e',1,'fz::Pipeline']]],
  ['categories_8',['Categories',['../stages_overview.html#autotoc_md101',1,'']]],
  ['category_20definitions_9',['Category definitions',['../how_to_add_a_stage.html#autotoc_md292',1,'']]],
  ['cd_20testing_10',['CI/CD Testing',['../md_docs_2docker.html#autotoc_md345',1,'']]],
  ['change_20checklist_11',['API change checklist',['../api_reference.html#autotoc_md267',1,'']]],
  ['checklist_12',['checklist',['../api_reference.html#autotoc_md267',1,'API change checklist'],['../how_to_add_a_stage.html#autotoc_md318',1,'Checklist']]],
  ['choose_20a_20location_13',['Step 1 — Choose a location',['../how_to_add_a_stage.html#autotoc_md291',1,'']]],
  ['chunking_14',['Chunking',['../stage_diff.html#autotoc_md75',1,'']]],
  ['ci_15',['Build Failures in CI',['../md_docs_2docker.html#autotoc_md355',1,'']]],
  ['ci_20cd_20testing_16',['CI/CD Testing',['../md_docs_2docker.html#autotoc_md345',1,'']]],
  ['citation_17',['Citation',['../index.html#autotoc_md20',1,'']]],
  ['cli_20dynamic_20builder_20optional_18',['Step 8 — Register in the CLI dynamic builder *(optional)*',['../how_to_add_a_stage.html#autotoc_md314',1,'']]],
  ['cmake_19',['Using from CMake',['../building_from_source.html#autotoc_md43',1,'']]],
  ['cmake_20options_20',['CMake Options',['../building_from_source.html#autotoc_md30',1,'']]],
  ['cmake_20presets_21',['CMake Presets',['../building_from_source.html#autotoc_md28',1,'']]],
  ['cmake_20recommended_22',['With CMake (Recommended)',['../md_docs_2docker.html#autotoc_md342',1,'']]],
  ['cmakelists_20txt_23',['Step 6 — Add to CMakeLists.txt',['../how_to_add_a_stage.html#autotoc_md308',1,'']]],
  ['coarse_24',['Coarse',['../huffman__stage_8h.html#ad50d9a4b3988beaf4321dd448fc2f817a1fb282a269a2bc94abc136c0511daa59',1,'fz']]],
  ['code_5ftype_25',['code_type',['../structfz_1_1QuantizerConfig.html#a6cab689ae14f2b4966cdcb70532e21fa',1,'fz::QuantizerConfig::code_type'],['../structfz_1_1LorenzoQuantConfig.html#abe1a985065f5f4e45738258ca38a9045',1,'fz::LorenzoQuantConfig::code_type']]],
  ['coder_20stages_26',['Coder stages',['../stage_coders.html',1,'stages_overview']]],
  ['coding_27',['Huffman Entropy Coding',['../libpressio_python.html#autotoc_md386',1,'']]],
  ['collecttimings_28',['collectTimings',['../classfz_1_1CompressionDAG.html#abd7628c59cd50a130de2e8c7cd54c6cf',1,'fz::CompressionDAG']]],
  ['command_20line_20interface_29',['Command Line Interface',['../cli_overview.html',1,'']]],
  ['common_20build_20examples_30',['Common Build Examples',['../building_from_source.html#autotoc_md32',1,'']]],
  ['common_20gotchas_31',['Common Gotchas',['../api_reference.html#autotoc_md262',1,'']]],
  ['common_20instantiations_32',['Common instantiations',['../stage_diff.html#autotoc_md76',1,'']]],
  ['common_20recipes_33',['Common Recipes',['../libpressio_python.html#autotoc_md390',1,'']]],
  ['compare_20and_20report_34',['Decompress, compare, and report',['../cli_overview.html#autotoc_md228',1,'']]],
  ['compatibility_35',['CUDA Graph compatibility',['../how_to_add_a_stage.html#autotoc_md298',1,'']]],
  ['complete_20examples_36',['Complete Examples',['../config_file_overview.html#autotoc_md222',1,'']]],
  ['compress_37',['compress',['../classfz_1_1Pipeline.html#afdf84d64278967a1e4943e321c6663d7',1,'fz::Pipeline::compress(const void *d_input, size_t input_size, void **d_output, size_t *output_size, cudaStream_t stream=0)'],['../classfz_1_1Pipeline.html#a5a9cde773f23ccc6958304539f3adf66',1,'fz::Pipeline::compress(const void *d_input, size_t input_size, void *d_output_buf, size_t output_buf_capacity, size_t *actual_output_size, cudaStream_t stream=0)']]],
  ['compressed_5fsize_38',['compressed_size',['../structfz_1_1FZMHeaderCore.html#a9c4c297b17531e51966df22f5b3b93bb',1,'fz::FZMHeaderCore']]],
  ['compression_39',['compression',['../api_reference.html#autotoc_md245',1,'Compression'],['../architecture.html#autotoc_md280',1,'Compression'],['../stage_lorenzo_quant.html#autotoc_md123',1,'Output ports (compression)'],['../stage_quantizer.html#autotoc_md151',1,'Output ports (compression)']]],
  ['compressiondag_40',['compressiondag',['../architecture.html#autotoc_md276',1,'CompressionDAG'],['../classfz_1_1CompressionDAG.html',1,'fz::CompressionDAG']]],
  ['compressor_20config_20file_41',['Compressor Config File',['../index.html#autotoc_md14',1,'']]],
  ['compressor_2eh_42',['compressor.h',['../compressor_8h.html',1,'']]],
  ['compute_20sanitizer_43',['CUDA Compute Sanitizer',['../building_from_source.html#autotoc_md38',1,'']]],
  ['computeheadersize_44',['computeHeaderSize',['../structfz_1_1FZMHeaderCore.html#a16cf12a6e8d91fd9ec385fc6fe6bfaff',1,'fz::FZMHeaderCore']]],
  ['computetopopoolsize_45',['computeTopoPoolSize',['../classfz_1_1CompressionDAG.html#a453300d012b4f20a7d75d11e4b6c4ba5',1,'fz::CompressionDAG']]],
  ['config_46',['config',['../cli_overview.html#autotoc_md229',1,'Branched pipelines via TOML config'],['../structfz_1_1QuantizerStage_1_1Config.html',1,'fz::QuantizerStage&lt; TInput, TCode &gt;::Config'],['../structfz_1_1LorenzoQuantStage_1_1Config.html',1,'fz::LorenzoQuantStage&lt; TInput, TCode &gt;::Config']]],
  ['config_20file_47',['config file',['../index.html#autotoc_md14',1,'Compressor Config File'],['../libpressio_python.html#autotoc_md403',1,'TOML Config File']]],
  ['config_20loader_48',['Step 7 — Register in the TOML config loader',['../how_to_add_a_stage.html#autotoc_md312',1,'']]],
  ['config_2eh_49',['config.h',['../config_8h.html',1,'']]],
  ['config_5fsize_50',['config_size',['../structfz_1_1FZMStageInfo.html#ac9bc5ceeb7c54ada7c97a89a28bd358f',1,'fz::FZMStageInfo::config_size'],['../structfz_1_1FZMBufferEntry.html#a8f103769a3e7b1f0c8be631ed7af84bc',1,'fz::FZMBufferEntry::config_size']]],
  ['configuration_51',['TOML configuration',['../stage_huffman.html#autotoc_md92',1,'']]],
  ['configuration_20before_20finalize_52',['Configuration (before finalize())',['../api_reference.html#autotoc_md241',1,'']]],
  ['configuration_20files_53',['Pipeline Configuration Files',['../config_file_overview.html',1,'']]],
  ['configurestreams_54',['configureStreams',['../classfz_1_1CompressionDAG.html#ac1d4d81f4fd43307c83f65053bc1eb67',1,'fz::CompressionDAG']]],
  ['connect_55',['connect',['../classfz_1_1Pipeline.html#a9c6db9510443efd2999b5af3405d1b78',1,'fz::Pipeline::connect(Stage *dependent, Stage *producer, const std::string &amp;output_name=&quot;output&quot;)'],['../classfz_1_1Pipeline.html#a1a61b6d5245b7a9ab2446fbea8c77880',1,'fz::Pipeline::connect(Stage *dependent, const std::vector&lt; Stage * &gt; &amp;producers)']]],
  ['connectexistingoutput_56',['connectExistingOutput',['../classfz_1_1CompressionDAG.html#ae413809eef19637aa3256a1d583ee339',1,'fz::CompressionDAG']]],
  ['connections_20format_57',['Connections format',['../libpressio_python.html#autotoc_md375',1,'']]],
  ['constraints_20abs_20noa_20only_58',['Inplace outlier constraints (ABS/NOA only)',['../stage_quantizer.html#autotoc_md158',1,'']]],
  ['construction_59',['Construction',['../api_reference.html#autotoc_md239',1,'']]],
  ['cpu–gpu_20movement_20pattern_60',['Execution flow (CPU–GPU movement pattern)',['../stage_huffman.html#huffman-execution',1,'']]],
  ['create_20and_20activate_20a_20spack_20environment_61',['Create and activate a spack environment',['../libpressio_python.html#autotoc_md362',1,'']]],
  ['createstage_62',['createStage',['../stage__factory_8h.html#a0e37a3291dc2265bfc9fbbb449dea787',1,'fz']]],
  ['critical_20ordering_20rule_63',['critical ordering rule',['../stage_lorenzo.html#autotoc_md112',1,'Dimension setup — critical ordering rule'],['../stage_lorenzo_quant.html#autotoc_md127',1,'Dimension setup — critical ordering rule']]],
  ['cu_64',['Step 3 — Write the implementation (&lt;name&gt;_stage.cu)',['../how_to_add_a_stage.html#autotoc_md301',1,'']]],
  ['cuda_20compute_20sanitizer_65',['CUDA Compute Sanitizer',['../building_from_source.html#autotoc_md38',1,'']]],
  ['cuda_20graph_20capture_66',['cuda graph capture',['../api_reference.html#autotoc_md258',1,'CUDA Graph Capture'],['../stage_lorenzo_quant.html#autotoc_md129',1,'Value base and CUDA Graph capture'],['../stage_quantizer.html#autotoc_md163',1,'Value base and CUDA Graph capture']]],
  ['cuda_20graph_20compatibility_67',['CUDA Graph compatibility',['../how_to_add_a_stage.html#autotoc_md298',1,'']]],
  ['cuda_20graph_20mode_68',['CUDA Graph Mode',['../libpressio_python.html#autotoc_md398',1,'']]],
  ['cuda_20graph_20support_69',['CUDA Graph Support',['../index.html#autotoc_md12',1,'']]],
  ['cuda_5fcheck_2eh_70',['cuda_check.h',['../cuda__check_8h.html',1,'']]],
  ['cusz_20style_20lorenzo_20huffman_71',['cuSZ-style Lorenzo + Huffman',['../stage_huffman.html#autotoc_md90',1,'']]],
  ['cuszp_20style_72',['Typical pipeline (cuSZp-style)',['../stage_lorenzo.html#autotoc_md114',1,'']]]
];
