var searchData=
[
  ['o_0',['o',['../index.html#autotoc_md16',1,'File I/O'],['../api_reference.html#autotoc_md256',1,'File I/O']]],
  ['on_20smooth_20data_1',['Lorenzo + RZE (best ratio on smooth data)',['../libpressio_python.html#autotoc_md392',1,'']]],
  ['one_20entry_20per_20stage_2',['[[stage]] &amp;ndash; one entry per stage',['../config_file_overview.html#autotoc_md208',1,'']]],
  ['one_20per_20buffer_3',['FZMBufferEntry (256 bytes, one per buffer)',['../fzm_format.html#autotoc_md328',1,'']]],
  ['one_20per_20stage_4',['FZMStageInfo (256 bytes, one per stage)',['../fzm_format.html#autotoc_md326',1,'']]],
  ['onfinalize_5',['onfinalize',['../classfz_1_1HuffmanStage.html#a6814fe1d82e31f00a703cf57c16f9e7e',1,'fz::HuffmanStage::onFinalize()'],['../classfz_1_1Stage.html#a6299d16e31d44e1419ce7be8a8ebb2f7',1,'fz::Stage::onFinalize()']]],
  ['only_6',['only',['../stage_quantizer.html#autotoc_md158',1,'Inplace outlier constraints (ABS/NOA only)'],['../libpressio_python.html#autotoc_md394',1,'Quantizer with Inplace Outliers (float32 only)']]],
  ['optional_7',['Step 8 — Register in the CLI dynamic builder *(optional)*',['../how_to_add_a_stage.html#autotoc_md314',1,'']]],
  ['options_8',['options',['../building_from_source.html#autotoc_md30',1,'CMake Options'],['../libpressio_python.html#autotoc_md373',1,'Pipeline Options']]],
  ['ordering_20rule_9',['ordering rule',['../stage_lorenzo_quant.html#autotoc_md127',1,'Dimension setup — critical ordering rule'],['../stage_lorenzo.html#autotoc_md112',1,'Dimension setup — critical ordering rule']]],
  ['outlier_20constraints_20abs_20noa_20only_10',['Inplace outlier constraints (ABS/NOA only)',['../stage_quantizer.html#autotoc_md158',1,'']]],
  ['outlier_20mode_201_20output_11',['Inplace outlier mode (1 output)',['../stage_quantizer.html#autotoc_md153',1,'']]],
  ['outlier_20pipeline_12',['Inplace outlier pipeline',['../stage_quantizer.html#autotoc_md167',1,'']]],
  ['outlier_5fcapacity_13',['outlier_capacity',['../structfz_1_1LorenzoQuantStage_1_1Config.html#aace97e92760f74875381ff6d16f42605',1,'fz::LorenzoQuantStage::Config::outlier_capacity'],['../structfz_1_1QuantizerStage_1_1Config.html#a1f660d7a08b5704dbe83997c6c1ac707',1,'fz::QuantizerStage::Config::outlier_capacity']]],
  ['outlier_5fcount_14',['outlier_count',['../structfz_1_1LorenzoQuantConfig.html#ad500a5efc9552c6fbfd6ca40096f0e9d',1,'fz::LorenzoQuantConfig::outlier_count'],['../structfz_1_1QuantizerConfig.html#a52a85cd7b0baccbe8a4ad93d5e8828a5',1,'fz::QuantizerConfig::outlier_count']]],
  ['outlier_5fthreshold_15',['outlier_threshold',['../structfz_1_1QuantizerConfig.html#ad7b585e3114a7fcc04782a204ac0d9a7',1,'fz::QuantizerConfig::outlier_threshold'],['../structfz_1_1QuantizerStage_1_1Config.html#a05e76b12c7d44b2759f315eb11b49ae9',1,'fz::QuantizerStage::Config::outlier_threshold']]],
  ['outliers_16',['Why REL does not support inplace outliers',['../stage_quantizer.html#autotoc_md161',1,'']]],
  ['outliers_20float32_20only_17',['Quantizer with Inplace Outliers (float32 only)',['../libpressio_python.html#autotoc_md394',1,'']]],
  ['output_18',['output',['../building_from_source.html#autotoc_md34',1,'Binary Output'],['../index.html#autotoc_md10',1,'Caller-Allocated Output'],['../api_reference.html#autotoc_md251',1,'Caller-owned output'],['../api_reference.html#autotoc_md247',1,'Caller-owned output'],['../stage_quantizer.html#autotoc_md153',1,'Inplace outlier mode (1 output)'],['../stage_rle.html#autotoc_md179',1,'Stream layout (forward output)'],['../stage_rze.html#autotoc_md189',1,'Stream layout (forward output)']]],
  ['output_20default_19',['output default',['../api_reference.html#autotoc_md250',1,'Pool-owned output (default)'],['../api_reference.html#autotoc_md246',1,'Pool-owned output (default)']]],
  ['output_20locations_20',['Shared output locations',['../how_to_add_a_stage.html#autotoc_md302',1,'']]],
  ['output_20port_20names_21',['Stage output port names',['../libpressio_python.html#autotoc_md401',1,'']]],
  ['output_20ports_20compression_22',['output ports compression',['../stage_lorenzo_quant.html#autotoc_md123',1,'Output ports (compression)'],['../stage_quantizer.html#autotoc_md151',1,'Output ports (compression)']]],
  ['output_20stages_23',['Multi-output stages',['../how_to_add_a_stage.html#autotoc_md295',1,'']]],
  ['output_5fbuffer_5fids_24',['output_buffer_ids',['../structfz_1_1FZMStageInfo.html#af834d5d4804101f4c52c021cc3cbdf3e',1,'fz::FZMStageInfo']]],
  ['output_5fbytes_25',['output_bytes',['../structfz_1_1StageTimingResult.html#a358a949d083bf2afa48fbc59b7524c94',1,'fz::StageTimingResult::output_bytes'],['../structfz_1_1PipelinePerfResult.html#a5ba0b678747d0630917a5ac7227a3151',1,'fz::PipelinePerfResult::output_bytes']]],
  ['outputs_26',['outputs',['../libpressio_python.html#autotoc_md400',1,'Exposing Stage Outputs'],['../stage_quantizer.html#autotoc_md152',1,'Normal mode (4 outputs)']]],
  ['overview_27',['overview',['../architecture.html',1,'Architecture Overview'],['../how_to_add_a_stage.html#autotoc_md289',1,'Overview'],['../md_docs_2docker.html#autotoc_md338',1,'Overview'],['../index.html#autotoc_md0',1,'Overview']]],
  ['owned_20output_28',['owned output',['../api_reference.html#autotoc_md251',1,'Caller-owned output'],['../api_reference.html#autotoc_md247',1,'Caller-owned output']]],
  ['owned_20output_20default_29',['owned output default',['../api_reference.html#autotoc_md250',1,'Pool-owned output (default)'],['../api_reference.html#autotoc_md246',1,'Pool-owned output (default)']]],
  ['ownership_30',['Memory Ownership',['../architecture.html#autotoc_md283',1,'']]],
  ['ownership_20summary_31',['Memory Ownership Summary',['../api_reference.html#autotoc_md254',1,'']]]
];
