var searchData=
[
  ['tag_0',['tag',['../structfz_1_1AllocationInfo.html#acaf33b3fee32287c4f44085646bbf611',1,'fz::AllocationInfo']]],
  ['targets_1',['Full Build with All Targets',['../md_docs_2docker.html#autotoc_md517',1,'']]],
  ['tcode_20sizeof_20tinput_2',['2. sizeof(TCode) == sizeof(TInput)',['../stage_quantizer.html#autotoc_md287',1,'']]],
  ['template_20parameter_3',['template parameter',['../stage_lorenzo.html#autotoc_md214',1,'Template parameter'],['../stage_huffman.html#autotoc_md189',1,'Template parameter'],['../stage_adaptive_bitpack.html#autotoc_md59',1,'Template parameter'],['../stage_bitpack.html#autotoc_md118',1,'Template parameter'],['../stage_rle.html#autotoc_md300',1,'Template parameter'],['../stage_tiled_lorenzo.html#autotoc_md339',1,'Template parameter']]],
  ['template_20parameters_4',['template parameters',['../stage_diff.html#autotoc_md151',1,'Template parameters'],['../stage_bitplane_rze.html#autotoc_md130',1,'Template parameters'],['../stage_zigzag.html#autotoc_md355',1,'Template parameters'],['../stage_ginterp.html#autotoc_md166',1,'Template parameters'],['../stage_quantizer.html#autotoc_md270',1,'Template parameters'],['../stage_negabinary.html#autotoc_md259',1,'Template parameters'],['../stage_lorenzo_quant.html#autotoc_md227',1,'Template parameters']]],
  ['test_20suite_5',['Running the Test Suite',['../md_docs_2docker.html#autotoc_md516',1,'']]],
  ['testing_6',['testing',['../md_docs_2docker.html#autotoc_md515',1,'CI/CD Testing'],['../building_from_source.html#autotoc_md46',1,'Testing']]],
  ['tests_7',['Step 9 — Write tests',['../how_to_add_a_stage.html#autotoc_md486',1,'']]],
  ['the_20cli_20dynamic_20builder_20optional_8',['Step 8 — Register in the CLI dynamic builder *(optional)*',['../how_to_add_a_stage.html#autotoc_md482',1,'']]],
  ['the_20docker_20image_9',['Building the Docker Image',['../md_docs_2docker.html#autotoc_md509',1,'']]],
  ['the_20factory_10',['Step 5 — Register in the factory',['../how_to_add_a_stage.html#autotoc_md474',1,'']]],
  ['the_20graph_11',['Building the Graph',['../api_reference.html#autotoc_md408',1,'']]],
  ['the_20header_20name_20_5fstage_20h_12',['Step 2 — Write the header (&lt;name&gt;_stage.h)',['../how_to_add_a_stage.html#autotoc_md462',1,'']]],
  ['the_20implementation_20name_20_5fstage_20cu_13',['Step 3 — Write the implementation (&lt;name&gt;_stage.cu)',['../how_to_add_a_stage.html#autotoc_md469',1,'']]],
  ['the_20libpressio_20source_20fork_14',['Point spack at the libpressio source fork',['../libpressio_python.html#autotoc_md533',1,'']]],
  ['the_20library_15',['Reading a File Without the Library',['../fzm_format.html#autotoc_md504',1,'']]],
  ['the_20pre_20installed_20library_16',['Using the Pre-Installed Library',['../md_docs_2docker.html#autotoc_md510',1,'']]],
  ['the_20public_20header_17',['Step 6b — Export in the public header',['../how_to_add_a_stage.html#autotoc_md478',1,'']]],
  ['the_20source_18',['Getting the Source',['../building_from_source.html#autotoc_md34',1,'']]],
  ['the_20spack_20package_20repos_19',['Add the spack package repos',['../libpressio_python.html#autotoc_md531',1,'']]],
  ['the_20stagetype_20',['Step 4 — Register the StageType',['../how_to_add_a_stage.html#autotoc_md472',1,'']]],
  ['the_20test_20suite_21',['Running the Test Suite',['../md_docs_2docker.html#autotoc_md516',1,'']]],
  ['the_20toml_20config_20loader_22',['Step 7 — Register in the TOML config loader',['../how_to_add_a_stage.html#autotoc_md480',1,'']]],
  ['this_20stage_20is_20fused_20no_20standalone_20predictor_23',['Why this stage is fused (no standalone predictor)',['../stage_ginterp.html#autotoc_md164',1,'']]],
  ['thread_20safety_24',['Thread Safety',['../index.html#autotoc_md28',1,'']]],
  ['threadsanitizer_25',['ThreadSanitizer',['../building_from_source.html#autotoc_md49',1,'']]],
  ['throughput_5fgbs_26',['throughput_gbs',['../structfz_1_1PipelinePerfResult.html#a49ca691a5fbab35385471ab4a7d8f171',1,'fz::PipelinePerfResult::throughput_gbs()'],['../structfz_1_1StageTimingResult.html#ab038f243874a6848249dbbcb1fadbbcb',1,'fz::StageTimingResult::throughput_gbs()']]],
  ['tile_20major_20output_27',['Tile-major output',['../stage_tiled_lorenzo.html#autotoc_md337',1,'']]],
  ['tile_5fx_28',['tile_x',['../structfz_1_1TiledLorenzoConfig.html#a8671b341cf900a6d3860c5666c238da3',1,'fz::TiledLorenzoConfig']]],
  ['tile_5fy_29',['tile_y',['../structfz_1_1TiledLorenzoConfig.html#a827d837d3473e45fd18ae0da2563f420',1,'fz::TiledLorenzoConfig']]],
  ['tile_5fz_30',['tile_z',['../structfz_1_1TiledLorenzoConfig.html#a792daab466f170d61d91bca0122dc2a7',1,'fz::TiledLorenzoConfig']]],
  ['tiled_5florenzo_31',['TILED_LORENZO',['../namespacefz.html#a91f5c5157c5ae2919b8c6875d805aa72aaa349ce98424c0a63e01cb5e927d2ed8',1,'fz']]],
  ['tiled_5florenzo_5fstage_2eh_32',['tiled_lorenzo_stage.h',['../tiled__lorenzo__stage_8h.html',1,'']]],
  ['tiledlorenzoconfig_33',['TiledLorenzoConfig',['../structfz_1_1TiledLorenzoConfig.html',1,'fz']]],
  ['tiledlorenzostage_34',['tiledlorenzostage',['../classfz_1_1TiledLorenzoStage.html',1,'fz::TiledLorenzoStage&lt; T &gt;'],['../stage_tiled_lorenzo.html',1,'TiledLorenzoStage']]],
  ['tinput_35',['2. sizeof(TCode) == sizeof(TInput)',['../stage_quantizer.html#autotoc_md287',1,'']]],
  ['to_20add_20a_20new_20stage_36',['How to Add a New Stage',['../how_to_add_a_stage.html',1,'']]],
  ['to_20bitshufflestage_20rzestage_37',['to bitshufflestage rzestage',['../classfz_1_1BitplaneRZEStage.html#autotoc_md0',1,'Relationship to BitshuffleStage + RZEStage'],['../stage_bitplane_rze.html#autotoc_md129',1,'Relationship to BitshuffleStage + RZEStage']]],
  ['to_20cmakelists_20txt_38',['Step 6 — Add to CMakeLists.txt',['../how_to_add_a_stage.html#autotoc_md476',1,'']]],
  ['tokens_39',['Stage Tokens',['../libpressio_python.html#autotoc_md547',1,'']]],
  ['toml_40',['toml',['../stage_adaptive_bitpack.html#autotoc_md71',1,'TOML'],['../stage_tiled_lorenzo.html#autotoc_md349',1,'TOML']]],
  ['toml_20config_41',['Branched pipelines via TOML config',['../cli_overview.html#autotoc_md393',1,'']]],
  ['toml_20config_20file_42',['TOML Config File',['../libpressio_python.html#autotoc_md573',1,'']]],
  ['toml_20config_20loader_43',['Step 7 — Register in the TOML config loader',['../how_to_add_a_stage.html#autotoc_md480',1,'']]],
  ['toml_20configuration_44',['toml configuration',['../stage_ginterp.html#autotoc_md181',1,'TOML configuration'],['../stage_ans.html#autotoc_md104',1,'TOML configuration'],['../stage_merge.html#autotoc_md253',1,'TOML configuration'],['../stage_adm.html#autotoc_md83',1,'TOML configuration'],['../stage_bitplane_rze.html#autotoc_md135',1,'TOML configuration'],['../stage_huffman.html#autotoc_md199',1,'TOML configuration']]],
  ['toml_20schema_45',['TOML Schema',['../config_file_overview.html#autotoc_md368',1,'']]],
  ['trace_46',['TRACE',['../namespacefz.html#aed168b7f4825b1f0f5b87507949fa161a2d3e4144aa384b18849ab9a8abad74d6',1,'fz']]],
  ['transform_20stages_47',['Transform stages',['../stage_transforms.html',1,'stages_overview']]],
  ['transforms_48',['Zigzag and Negabinary Transforms',['../libpressio_python.html#autotoc_md551',1,'']]],
  ['trim_49',['trim',['../classfz_1_1MemoryPool.html#a2671327aa18232aab2d18f37b52c1ad8',1,'fz::MemoryPool']]],
  ['troubleshooting_50',['Troubleshooting',['../md_docs_2docker.html#autotoc_md522',1,'']]],
  ['tt_20bklen_20tt_51',['Setting &lt;tt&gt;bklen&lt;/tt&gt;',['../stage_huffman.html#autotoc_md193',1,'']]],
  ['tt_20decompressinto_20tt_20async_52',['Stream-concurrent decode (&lt;tt&gt;decompressInto&lt;/tt&gt;, async)',['../api_reference.html#autotoc_md418',1,'']]],
  ['tt_20float_20tt_20tt_20double_20tt_20and_20shared_20memory_53',['Precision (&lt;tt&gt;float&lt;/tt&gt; / &lt;tt&gt;double&lt;/tt&gt;) and shared memory',['../classfz_1_1GInterpStage.html#autotoc_md3',1,'']]],
  ['tt_20nbits_20tt_54',['tt nbits tt',['../stage_bitpack.html#autotoc_md127',1,'Auto-detect &lt;tt&gt;nbits&lt;/tt&gt;'],['../stage_bitpack.html#autotoc_md126',1,'Manual &lt;tt&gt;nbits&lt;/tt&gt;']]],
  ['tune_55',['Radius auto-tune',['../stage_ginterp.html#autotoc_md171',1,'']]],
  ['tune_20default_20behaviour_56',['Radius auto-tune (default behaviour)',['../classfz_1_1GInterpStage.html#autotoc_md4',1,'']]],
  ['tuning_57',['Auto-tuning',['../stage_ginterp.html#autotoc_md172',1,'']]],
  ['txt_58',['Step 6 — Add to CMakeLists.txt',['../how_to_add_a_stage.html#autotoc_md476',1,'']]],
  ['types_59',['Stage Types',['../config_file_overview.html#autotoc_md372',1,'']]],
  ['typical_20pipeline_60',['typical pipeline',['../stage_bitplane_rze.html#autotoc_md134',1,'Typical pipeline'],['../stage_huffman.html#autotoc_md195',1,'Typical pipeline'],['../stage_diff.html#autotoc_md161',1,'Typical pipeline'],['../stage_rle.html#autotoc_md306',1,'Typical pipeline'],['../stage_rre.html#autotoc_md318',1,'Typical pipeline'],['../stage_rze.html#autotoc_md330',1,'Typical pipeline'],['../stage_bitshuffle.html#autotoc_md145',1,'Typical pipeline'],['../stage_negabinary.html#autotoc_md266',1,'Typical pipeline'],['../stage_bitpack.html#autotoc_md125',1,'Typical pipeline'],['../stage_zigzag.html#autotoc_md362',1,'Typical pipeline'],['../stage_lorenzo_quant.html#autotoc_md240',1,'Typical pipeline'],['../stage_adm.html#autotoc_md79',1,'Typical pipeline'],['../stage_ginterp.html#autotoc_md179',1,'Typical pipeline'],['../stage_ans.html#autotoc_md100',1,'Typical pipeline']]],
  ['typical_20pipeline_20cusz_20hi_20cr_20mode_20merged_20blob_61',['Typical pipeline (cuSZ-Hi cr-mode merged blob)',['../stage_merge.html#autotoc_md251',1,'']]],
  ['typical_20pipeline_20cuszp_20style_62',['typical pipeline cuszp style',['../stage_lorenzo.html#autotoc_md223',1,'Typical pipeline (cuSZp-style)'],['../stage_adaptive_bitpack.html#autotoc_md69',1,'Typical pipeline (cuSZp-style)']]],
  ['typical_20pipeline_20cuszp3_63',['Typical pipeline (cuSZp3)',['../stage_tiled_lorenzo.html#autotoc_md347',1,'']]],
  ['typical_20pipelines_64',['Typical pipelines',['../stage_quantizer.html#autotoc_md292',1,'']]]
];
