var searchData=
[
  ['c_20api_20usage_0',['C++ API Usage',['../index.html#autotoc_md14',1,'']]],
  ['calculatestatistics_1',['calculateStatistics',['../namespacefz.html#a1e378f0769aaa07fee908c8a2b52a370',1,'fz']]],
  ['caller_20allocated_20buffer_20no_20internal_20allocation_2',['Caller-allocated buffer (no internal allocation)',['../api_reference.html#autotoc_md417',1,'']]],
  ['caller_20allocated_20output_3',['Caller-Allocated Output',['../index.html#autotoc_md18',1,'']]],
  ['caller_20owned_20output_4',['caller owned output',['../api_reference.html#autotoc_md412',1,'Caller-owned output'],['../api_reference.html#autotoc_md416',1,'Caller-owned output']]],
  ['cannot_20find_20fzgpumodules_5',['find_package Cannot Find FZGPUModules',['../md_docs_2docker.html#autotoc_md524',1,'']]],
  ['capture_6',['capture',['../api_reference.html#autotoc_md426',1,'CUDA Graph Capture'],['../stage_rre.html#autotoc_md316',1,'Graph capture'],['../stage_quantizer.html#autotoc_md290',1,'Value base and CUDA Graph capture'],['../stage_lorenzo_quant.html#autotoc_md238',1,'Value base and CUDA Graph capture']]],
  ['capturegraph_7',['captureGraph',['../classfz_1_1Pipeline.html#ae6fcaa9d197469e28e520897a1a91a0e',1,'fz::Pipeline']]],
  ['categories_8',['Categories',['../stages_overview.html#autotoc_md210',1,'']]],
  ['category_20definitions_9',['Category definitions',['../how_to_add_a_stage.html#autotoc_md460',1,'']]],
  ['cd_20testing_10',['CI/CD Testing',['../md_docs_2docker.html#autotoc_md515',1,'']]],
  ['change_20checklist_11',['API change checklist',['../api_reference.html#autotoc_md435',1,'']]],
  ['checklist_12',['checklist',['../api_reference.html#autotoc_md435',1,'API change checklist'],['../how_to_add_a_stage.html#autotoc_md488',1,'Checklist']]],
  ['choose_20a_20location_13',['Step 1 — Choose a location',['../how_to_add_a_stage.html#autotoc_md459',1,'']]],
  ['chunk_5fsize_14',['chunk_size',['../structfz_1_1bitplane__rze_1_1Config.html#aa04cf7fed0dccc8e87602c97cdf19dec',1,'fz::bitplane_rze::Config']]],
  ['chunking_15',['Chunking',['../stage_diff.html#autotoc_md156',1,'']]],
  ['ci_16',['Build Failures in CI',['../md_docs_2docker.html#autotoc_md525',1,'']]],
  ['ci_20cd_20testing_17',['CI/CD Testing',['../md_docs_2docker.html#autotoc_md515',1,'']]],
  ['citation_18',['Citation',['../index.html#autotoc_md30',1,'']]],
  ['cli_20dynamic_20builder_20optional_19',['Step 8 — Register in the CLI dynamic builder *(optional)*',['../how_to_add_a_stage.html#autotoc_md482',1,'']]],
  ['cmake_20',['Using from CMake',['../building_from_source.html#autotoc_md53',1,'']]],
  ['cmake_20options_21',['CMake Options',['../building_from_source.html#autotoc_md40',1,'']]],
  ['cmake_20presets_22',['CMake Presets',['../building_from_source.html#autotoc_md38',1,'']]],
  ['cmake_20recommended_23',['With CMake (Recommended)',['../md_docs_2docker.html#autotoc_md512',1,'']]],
  ['cmakelists_20txt_24',['Step 6 — Add to CMakeLists.txt',['../how_to_add_a_stage.html#autotoc_md476',1,'']]],
  ['coarse_25',['Coarse',['../namespacefz.html#ad50d9a4b3988beaf4321dd448fc2f817a1fb282a269a2bc94abc136c0511daa59',1,'fz']]],
  ['code_5ftype_26',['code_type',['../structfz_1_1LorenzoQuantConfig.html#abe1a985065f5f4e45738258ca38a9045',1,'fz::LorenzoQuantConfig::code_type'],['../structfz_1_1QuantizerConfig.html#a6cab689ae14f2b4966cdcb70532e21fa',1,'fz::QuantizerConfig::code_type'],['../structfz_1_1GInterpConfig.html#adb149524e8ca516c11e0a8f82edf7012',1,'fz::GInterpConfig::code_type']]],
  ['coder_20stages_27',['Coder stages',['../stage_coders.html',1,'stages_overview']]],
  ['coding_28',['Huffman Entropy Coding',['../libpressio_python.html#autotoc_md556',1,'']]],
  ['collecttimings_29',['collectTimings',['../classfz_1_1CompressionDAG.html#abd7628c59cd50a130de2e8c7cd54c6cf',1,'fz::CompressionDAG']]],
  ['command_20line_20interface_30',['Command Line Interface',['../cli_overview.html',1,'']]],
  ['common_20build_20examples_31',['Common Build Examples',['../building_from_source.html#autotoc_md42',1,'']]],
  ['common_20gotchas_32',['Common Gotchas',['../api_reference.html#autotoc_md430',1,'']]],
  ['common_20instantiations_33',['Common instantiations',['../stage_diff.html#autotoc_md157',1,'']]],
  ['common_20recipes_34',['Common Recipes',['../libpressio_python.html#autotoc_md560',1,'']]],
  ['compare_20and_20report_35',['Decompress, compare, and report',['../cli_overview.html#autotoc_md392',1,'']]],
  ['compatibility_36',['compatibility',['../how_to_add_a_stage.html#autotoc_md466',1,'CUDA Graph compatibility'],['../stage_adaptive_bitpack.html#autotoc_md67',1,'Graph compatibility'],['../stage_tiled_lorenzo.html#autotoc_md345',1,'Graph compatibility'],['../stage_bitplane_rze.html#autotoc_md132',1,'Graph compatibility']]],
  ['complete_20examples_37',['Complete Examples',['../config_file_overview.html#autotoc_md386',1,'']]],
  ['compress_38',['compress',['../classfz_1_1Pipeline.html#afdf84d64278967a1e4943e321c6663d7',1,'fz::Pipeline::compress(const void *d_input, size_t input_size, void **d_output, size_t *output_size, cudaStream_t stream=0)'],['../classfz_1_1Pipeline.html#a5a9cde773f23ccc6958304539f3adf66',1,'fz::Pipeline::compress(const void *d_input, size_t input_size, void *d_output_buf, size_t output_buf_capacity, size_t *actual_output_size, cudaStream_t stream=0)'],['../index.html#autotoc_md26',1,'Decode-only pipelines (no warmup compress)'],['../api_reference.html#autotoc_md424',1,'Decode-only pipelines (no warmup compress)']]],
  ['compressed_5fsize_39',['compressed_size',['../structfz_1_1FZMHeaderCore.html#a9c4c297b17531e51966df22f5b3b93bb',1,'fz::FZMHeaderCore']]],
  ['compression_40',['compression',['../api_reference.html#autotoc_md410',1,'Compression'],['../architecture.html#autotoc_md448',1,'Compression'],['../stage_quantizer.html#autotoc_md275',1,'Output ports (compression)'],['../stage_lorenzo_quant.html#autotoc_md232',1,'Output ports (compression)']]],
  ['compressiondag_41',['compressiondag',['../architecture.html#autotoc_md444',1,'CompressionDAG'],['../classfz_1_1CompressionDAG.html',1,'fz::CompressionDAG']]],
  ['compressor_20config_20file_42',['Compressor Config File',['../index.html#autotoc_md22',1,'']]],
  ['compressor_2eh_43',['compressor.h',['../compressor_8h.html',1,'']]],
  ['compute_20sanitizer_44',['CUDA Compute Sanitizer',['../building_from_source.html#autotoc_md48',1,'']]],
  ['computeheadersize_45',['computeHeaderSize',['../structfz_1_1FZMHeaderCore.html#a16cf12a6e8d91fd9ec385fc6fe6bfaff',1,'fz::FZMHeaderCore']]],
  ['computetopopoolsize_46',['computeTopoPoolSize',['../classfz_1_1CompressionDAG.html#a453300d012b4f20a7d75d11e4b6c4ba5',1,'fz::CompressionDAG']]],
  ['concurrent_20decode_20tt_20decompressinto_20tt_20async_47',['Stream-concurrent decode (&lt;tt&gt;decompressInto&lt;/tt&gt;, async)',['../api_reference.html#autotoc_md418',1,'']]],
  ['config_48',['config',['../cli_overview.html#autotoc_md393',1,'Branched pipelines via TOML config'],['../structfz_1_1QuantizerStage_1_1Config.html',1,'fz::QuantizerStage&lt; TInput, TCode &gt;::Config'],['../structfz_1_1LorenzoQuantStage_1_1Config.html',1,'fz::LorenzoQuantStage&lt; TInput, TCode &gt;::Config'],['../structfz_1_1bitplane__rze_1_1Config.html',1,'fz::bitplane_rze::Config'],['../structfz_1_1adaptive__bitpack_1_1Config.html',1,'fz::adaptive_bitpack::Config']]],
  ['config_20file_49',['config file',['../index.html#autotoc_md22',1,'Compressor Config File'],['../libpressio_python.html#autotoc_md573',1,'TOML Config File']]],
  ['config_20header_50',['config header',['../merge__stage_8h.html#autotoc_md7',1,'Serialized config header'],['../stage_merge.html#autotoc_md255',1,'Serialized config header']]],
  ['config_20loader_51',['Step 7 — Register in the TOML config loader',['../how_to_add_a_stage.html#autotoc_md480',1,'']]],
  ['config_2eh_52',['config.h',['../config_8h.html',1,'']]],
  ['config_5fsize_53',['config_size',['../structfz_1_1FZMStageInfo.html#ac9bc5ceeb7c54ada7c97a89a28bd358f',1,'fz::FZMStageInfo::config_size'],['../structfz_1_1FZMBufferEntry.html#a8f103769a3e7b1f0c8be631ed7af84bc',1,'fz::FZMBufferEntry::config_size']]],
  ['configuration_54',['configuration',['../stage_huffman.html#autotoc_md199',1,'TOML configuration'],['../stage_bitplane_rze.html#autotoc_md135',1,'TOML configuration'],['../stage_merge.html#autotoc_md253',1,'TOML configuration'],['../stage_ginterp.html#autotoc_md181',1,'TOML configuration'],['../stage_ans.html#autotoc_md104',1,'TOML configuration'],['../stage_adm.html#autotoc_md83',1,'TOML configuration']]],
  ['configuration_20before_20finalize_55',['Configuration (before finalize())',['../api_reference.html#autotoc_md406',1,'']]],
  ['configuration_20files_56',['Pipeline Configuration Files',['../config_file_overview.html',1,'']]],
  ['configure_57',['configure',['../bitplane__rze__kernels_8h.html#ae7901b1df02c85ca8438f1edb49ce2cf',1,'fz::bitplane_rze']]],
  ['configurestreams_58',['configureStreams',['../classfz_1_1CompressionDAG.html#ac1d4d81f4fd43307c83f65053bc1eb67',1,'fz::CompressionDAG']]],
  ['connect_59',['connect',['../classfz_1_1Pipeline.html#a1a61b6d5245b7a9ab2446fbea8c77880',1,'fz::Pipeline::connect(Stage *dependent, const std::vector&lt; Stage * &gt; &amp;producers)'],['../classfz_1_1Pipeline.html#a9c6db9510443efd2999b5af3405d1b78',1,'fz::Pipeline::connect(Stage *dependent, Stage *producer, const std::string &amp;output_name=&quot;output&quot;)']]],
  ['connectexistingoutput_60',['connectExistingOutput',['../classfz_1_1CompressionDAG.html#ae413809eef19637aa3256a1d583ee339',1,'fz::CompressionDAG']]],
  ['connections_20format_61',['Connections format',['../libpressio_python.html#autotoc_md545',1,'']]],
  ['constraints_20abs_20noa_20only_62',['Inplace outlier constraints (ABS/NOA only)',['../stage_quantizer.html#autotoc_md285',1,'']]],
  ['construction_63',['Construction',['../api_reference.html#autotoc_md404',1,'']]],
  ['cpu–gpu_20movement_20pattern_64',['cpu–gpu movement pattern',['../stage_adm.html#adm-execution',1,'Execution flow (CPU–GPU movement pattern)'],['../stage_ans.html#ans-execution',1,'Execution flow (CPU–GPU movement pattern)'],['../stage_huffman.html#huffman-execution',1,'Execution flow (CPU–GPU movement pattern)']]],
  ['cr_20mode_20merged_20blob_65',['Typical pipeline (cuSZ-Hi cr-mode merged blob)',['../stage_merge.html#autotoc_md251',1,'']]],
  ['create_20and_20activate_20a_20spack_20environment_66',['Create and activate a spack environment',['../libpressio_python.html#autotoc_md532',1,'']]],
  ['createstage_67',['createStage',['../namespacefz.html#a0e37a3291dc2265bfc9fbbb449dea787',1,'fz']]],
  ['critical_20ordering_20rule_68',['critical ordering rule',['../stage_lorenzo_quant.html#autotoc_md236',1,'Dimension setup — critical ordering rule'],['../stage_lorenzo.html#autotoc_md221',1,'Dimension setup — critical ordering rule']]],
  ['cu_69',['Step 3 — Write the implementation (&lt;name&gt;_stage.cu)',['../how_to_add_a_stage.html#autotoc_md469',1,'']]],
  ['cuda_20compute_20sanitizer_70',['CUDA Compute Sanitizer',['../building_from_source.html#autotoc_md48',1,'']]],
  ['cuda_20graph_20capture_71',['cuda graph capture',['../api_reference.html#autotoc_md426',1,'CUDA Graph Capture'],['../stage_lorenzo_quant.html#autotoc_md238',1,'Value base and CUDA Graph capture'],['../stage_quantizer.html#autotoc_md290',1,'Value base and CUDA Graph capture']]],
  ['cuda_20graph_20compatibility_72',['CUDA Graph compatibility',['../how_to_add_a_stage.html#autotoc_md466',1,'']]],
  ['cuda_20graph_20mode_73',['CUDA Graph Mode',['../libpressio_python.html#autotoc_md568',1,'']]],
  ['cuda_20graph_20support_74',['CUDA Graph Support',['../index.html#autotoc_md20',1,'']]],
  ['cuda_5fcheck_2eh_75',['cuda_check.h',['../cuda__check_8h.html',1,'']]],
  ['cusz_20hi_76',['cuSZ-Hi',['../acknowledgements.html#autotoc_md585',1,'']]],
  ['cusz_20hi_20cr_20mode_20merged_20blob_77',['Typical pipeline (cuSZ-Hi cr-mode merged blob)',['../stage_merge.html#autotoc_md251',1,'']]],
  ['cusz_20phf_78',['cuSZ / PHF',['../acknowledgements.html#autotoc_md581',1,'']]],
  ['cusz_20style_20lorenzo_20adm_20ans_20recommended_79',['cuSZ-style Lorenzo + ADM + ANS (recommended)',['../stage_adm.html#autotoc_md81',1,'']]],
  ['cusz_20style_20lorenzo_20ans_80',['cuSZ-style Lorenzo + ANS',['../stage_ans.html#autotoc_md102',1,'']]],
  ['cusz_20style_20lorenzo_20huffman_81',['cuSZ-style Lorenzo + Huffman',['../stage_huffman.html#autotoc_md197',1,'']]],
  ['cusz_5ftype_5fsubset_2eh_82',['cusz_type_subset.h',['../cusz__type__subset_8h.html',1,'']]],
  ['cuszp_20cuszp2_20cuszp3_83',['cuSZp / cuSZp2 / cuSZp3',['../acknowledgements.html#autotoc_md587',1,'']]],
  ['cuszp_20style_84',['cuszp style',['../stage_adaptive_bitpack.html#autotoc_md69',1,'Typical pipeline (cuSZp-style)'],['../stage_lorenzo.html#autotoc_md223',1,'Typical pipeline (cuSZp-style)']]],
  ['cuszp2_85',['Outlier selection (cuSZp2)',['../stage_adaptive_bitpack.html#autotoc_md62',1,'']]],
  ['cuszp2_20cuszp3_86',['cuSZp / cuSZp2 / cuSZp3',['../acknowledgements.html#autotoc_md587',1,'']]],
  ['cuszp2_20intentional_87',['Metadata difference from cuSZp2 (intentional)',['../stage_adaptive_bitpack.html#autotoc_md63',1,'']]],
  ['cuszp3_88',['cuszp3',['../acknowledgements.html#autotoc_md587',1,'cuSZp / cuSZp2 / cuSZp3'],['../stage_tiled_lorenzo.html#autotoc_md347',1,'Typical pipeline (cuSZp3)']]]
];
