var searchData=
[
  ['tag_0',['tag',['../structfz_1_1AllocationInfo.html#acaf33b3fee32287c4f44085646bbf611',1,'fz::AllocationInfo']]],
  ['targets_1',['Full Build with All Targets',['../md_docs_2docker.html#autotoc_md347',1,'']]],
  ['tcode_20sizeof_20tinput_2',['2. sizeof(TCode) == sizeof(TInput)',['../stage_quantizer.html#autotoc_md160',1,'']]],
  ['template_20parameter_3',['template parameter',['../stage_rle.html#autotoc_md171',1,'Template parameter'],['../stage_lorenzo.html#autotoc_md105',1,'Template parameter'],['../stage_huffman.html#autotoc_md82',1,'Template parameter'],['../stage_bitpack.html#autotoc_md49',1,'Template parameter']]],
  ['template_20parameters_4',['template parameters',['../stage_zigzag.html#autotoc_md193',1,'Template parameters'],['../stage_quantizer.html#autotoc_md146',1,'Template parameters'],['../stage_negabinary.html#autotoc_md135',1,'Template parameters'],['../stage_lorenzo_quant.html#autotoc_md118',1,'Template parameters'],['../stage_diff.html#autotoc_md70',1,'Template parameters']]],
  ['test_20suite_5',['Running the Test Suite',['../md_docs_2docker.html#autotoc_md346',1,'']]],
  ['testing_6',['testing',['../md_docs_2docker.html#autotoc_md345',1,'CI/CD Testing'],['../building_from_source.html#autotoc_md36',1,'Testing']]],
  ['tests_7',['Step 9 — Write tests',['../how_to_add_a_stage.html#autotoc_md316',1,'']]],
  ['the_20cli_20dynamic_20builder_20optional_8',['Step 8 — Register in the CLI dynamic builder *(optional)*',['../how_to_add_a_stage.html#autotoc_md314',1,'']]],
  ['the_20docker_20image_9',['Building the Docker Image',['../md_docs_2docker.html#autotoc_md339',1,'']]],
  ['the_20factory_10',['Step 5 — Register in the factory',['../how_to_add_a_stage.html#autotoc_md306',1,'']]],
  ['the_20graph_11',['Building the Graph',['../api_reference.html#autotoc_md243',1,'']]],
  ['the_20header_20name_20_5fstage_20h_12',['Step 2 — Write the header (&lt;name&gt;_stage.h)',['../how_to_add_a_stage.html#autotoc_md294',1,'']]],
  ['the_20implementation_20name_20_5fstage_20cu_13',['Step 3 — Write the implementation (&lt;name&gt;_stage.cu)',['../how_to_add_a_stage.html#autotoc_md301',1,'']]],
  ['the_20libpressio_20source_20fork_14',['Point spack at the libpressio source fork',['../libpressio_python.html#autotoc_md363',1,'']]],
  ['the_20library_15',['Reading a File Without the Library',['../fzm_format.html#autotoc_md334',1,'']]],
  ['the_20pre_20installed_20library_16',['Using the Pre-Installed Library',['../md_docs_2docker.html#autotoc_md340',1,'']]],
  ['the_20public_20header_17',['Step 6b — Export in the public header',['../how_to_add_a_stage.html#autotoc_md310',1,'']]],
  ['the_20source_18',['Getting the Source',['../building_from_source.html#autotoc_md24',1,'']]],
  ['the_20spack_20package_20repos_19',['Add the spack package repos',['../libpressio_python.html#autotoc_md361',1,'']]],
  ['the_20stagetype_20',['Step 4 — Register the StageType',['../how_to_add_a_stage.html#autotoc_md304',1,'']]],
  ['the_20test_20suite_21',['Running the Test Suite',['../md_docs_2docker.html#autotoc_md346',1,'']]],
  ['the_20toml_20config_20loader_22',['Step 7 — Register in the TOML config loader',['../how_to_add_a_stage.html#autotoc_md312',1,'']]],
  ['thread_20safety_23',['Thread Safety',['../index.html#autotoc_md18',1,'']]],
  ['threadsanitizer_24',['ThreadSanitizer',['../building_from_source.html#autotoc_md39',1,'']]],
  ['throughput_5fgbs_25',['throughput_gbs',['../structfz_1_1StageTimingResult.html#ab038f243874a6848249dbbcb1fadbbcb',1,'fz::StageTimingResult::throughput_gbs()'],['../structfz_1_1PipelinePerfResult.html#a49ca691a5fbab35385471ab4a7d8f171',1,'fz::PipelinePerfResult::throughput_gbs()']]],
  ['tinput_26',['2. sizeof(TCode) == sizeof(TInput)',['../stage_quantizer.html#autotoc_md160',1,'']]],
  ['to_20add_20a_20new_20stage_27',['How to Add a New Stage',['../how_to_add_a_stage.html',1,'']]],
  ['to_20cmakelists_20txt_28',['Step 6 — Add to CMakeLists.txt',['../how_to_add_a_stage.html#autotoc_md308',1,'']]],
  ['tokens_29',['Stage Tokens',['../libpressio_python.html#autotoc_md377',1,'']]],
  ['toml_20config_30',['Branched pipelines via TOML config',['../cli_overview.html#autotoc_md229',1,'']]],
  ['toml_20config_20file_31',['TOML Config File',['../libpressio_python.html#autotoc_md403',1,'']]],
  ['toml_20config_20loader_32',['Step 7 — Register in the TOML config loader',['../how_to_add_a_stage.html#autotoc_md312',1,'']]],
  ['toml_20configuration_33',['TOML configuration',['../stage_huffman.html#autotoc_md92',1,'']]],
  ['toml_20schema_34',['TOML Schema',['../config_file_overview.html#autotoc_md206',1,'']]],
  ['trace_35',['TRACE',['../log_8h.html#aed168b7f4825b1f0f5b87507949fa161a2d3e4144aa384b18849ab9a8abad74d6',1,'fz']]],
  ['transform_20stages_36',['Transform stages',['../stage_transforms.html',1,'stages_overview']]],
  ['transforms_37',['Zigzag and Negabinary Transforms',['../libpressio_python.html#autotoc_md381',1,'']]],
  ['trim_38',['trim',['../classfz_1_1MemoryPool.html#a2671327aa18232aab2d18f37b52c1ad8',1,'fz::MemoryPool']]],
  ['troubleshooting_39',['Troubleshooting',['../md_docs_2docker.html#autotoc_md352',1,'']]],
  ['tt_20bklen_20tt_40',['Setting &lt;tt&gt;bklen&lt;/tt&gt;',['../stage_huffman.html#autotoc_md86',1,'']]],
  ['tt_20nbits_20tt_41',['tt nbits tt',['../stage_bitpack.html#autotoc_md58',1,'Auto-detect &lt;tt&gt;nbits&lt;/tt&gt;'],['../stage_bitpack.html#autotoc_md57',1,'Manual &lt;tt&gt;nbits&lt;/tt&gt;']]],
  ['txt_42',['Step 6 — Add to CMakeLists.txt',['../how_to_add_a_stage.html#autotoc_md308',1,'']]],
  ['types_43',['Stage Types',['../config_file_overview.html#autotoc_md210',1,'']]],
  ['typical_20pipeline_44',['typical pipeline',['../stage_rle.html#autotoc_md177',1,'Typical pipeline'],['../stage_negabinary.html#autotoc_md142',1,'Typical pipeline'],['../stage_zigzag.html#autotoc_md200',1,'Typical pipeline'],['../stage_bitpack.html#autotoc_md56',1,'Typical pipeline'],['../stage_bitshuffle.html#autotoc_md66',1,'Typical pipeline'],['../stage_diff.html#autotoc_md78',1,'Typical pipeline'],['../stage_rze.html#autotoc_md187',1,'Typical pipeline'],['../stage_huffman.html#autotoc_md88',1,'Typical pipeline'],['../stage_lorenzo_quant.html#autotoc_md131',1,'Typical pipeline']]],
  ['typical_20pipeline_20cuszp_20style_45',['Typical pipeline (cuSZp-style)',['../stage_lorenzo.html#autotoc_md114',1,'']]],
  ['typical_20pipelines_46',['Typical pipelines',['../stage_quantizer.html#autotoc_md165',1,'']]]
];
