#!/usr/bin/env python3
"""
examples/plot_lorenzo_codes.py

Visualizes the uint16 code distributions produced by compare_lorenzo_modes.

Plots a 2×2 figure:
  Top row    — storage domain (uint16 values fed into Huffman)
    Left  : raw-delta codes across full [0, 65535] uint16 range
    Right : zigzag codes in compact [0, 2*radius] range
  Bottom row — semantic domain (signed delta values)
    Left  : raw-delta codes reinterpreted as signed int16
    Right : zigzag codes decoded back to signed deltas (should match left)

The top row explains WHY bklen requirements differ; the bottom row shows
that both modes encode the same underlying delta distribution.

Usage:
    python3 examples/plot_lorenzo_codes.py <rawdelta.u16> <zigzag.u16> [options]

Options:
    --radius N      Quantization radius used at compression (default: 512)
    --xlim N        Half-window shown in the signed-delta plots (default: auto)
    --out PATH      Save figure to file (e.g. --out hist.png); implies --no-show
    --no-show       Skip the interactive matplotlib window

Generated by: examples/compare_lorenzo_modes
"""

import argparse
import sys
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker


# ── helpers ──────────────────────────────────────────────────────────────────

def load_u16(path):
    with open(path, "rb") as fh:
        return np.frombuffer(fh.read(), dtype=np.uint16).copy()


def shannon_entropy_bits(codes):
    _, counts = np.unique(codes, return_counts=True)
    p = counts / counts.sum()
    return float(-np.sum(p * np.log2(p + 1e-300)))


def percentile_xlim(arr, pct=99.9):
    """Return symmetric limit covering pct% of values."""
    hi = float(np.percentile(np.abs(arr), pct))
    return max(1, int(hi) + 1)


def bar_histogram(ax, data, bins, color, label=None):
    """Plot a clean bar histogram with thin white edges."""
    counts, edges = np.histogram(data, bins=bins)
    centers = 0.5 * (edges[:-1] + edges[1:])
    ax.bar(centers, counts, width=np.diff(edges),
           color=color, edgecolor="white", linewidth=0.3,
           label=label, align="center")
    return counts


def annotate_box(ax, text, xy=(0.02, 0.97), ha="left", color="wheat"):
    ax.annotate(
        text, xy=xy, xycoords="axes fraction", va="top", ha=ha,
        fontsize=8.5,
        bbox=dict(boxstyle="round,pad=0.35", facecolor=color, alpha=0.75),
    )


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("rawdelta", help="Raw-delta uint16 binary file")
    ap.add_argument("zigzag",   help="Zigzag uint16 binary file")
    ap.add_argument("--radius", type=int, default=512,
                    help="Quantization radius (default: 512)")
    ap.add_argument("--xlim",   type=int, default=0,
                    help="Half-window for signed-delta plots; 0 = auto (default)")
    ap.add_argument("--out",    default=None,
                    help="Save figure to file instead of showing")
    ap.add_argument("--no-show", action="store_true",
                    help="Do not open interactive window")
    args = ap.parse_args()

    # ── load ─────────────────────────────────────────────────────────────────
    raw_u16 = load_u16(args.rawdelta)
    zig_u16 = load_u16(args.zigzag)
    n        = len(raw_u16)
    radius   = args.radius
    bklen_raw = 65536
    bklen_zig = 2 * radius

    # Signed-delta views
    raw_signed = raw_u16.view(np.int16).astype(np.int32)
    # zigzag decode: even k → +k/2, odd k → -(k+1)/2
    zig_s = zig_u16.astype(np.int32)
    zig_signed = np.where(zig_s % 2 == 0, zig_s // 2, -(zig_s + 1) // 2)

    H_raw = shannon_entropy_bits(raw_u16)
    H_zig = shannon_entropy_bits(zig_u16)
    # Entropy is the same for both (bijective map) — show one value
    assert abs(H_raw - H_zig) < 0.01, \
        f"entropy mismatch: {H_raw:.4f} vs {H_zig:.4f} — data inconsistency?"

    xlim = args.xlim if args.xlim > 0 else percentile_xlim(raw_signed)

    blue  = "#4C72B0"
    green = "#55A868"

    fig, axes = plt.subplots(2, 2, figsize=(14, 9))
    fig.suptitle(
        f"Lorenzo quantization code distributions  |  n = {n:,}  |  radius = {radius}  |"
        f"  entropy = {H_raw:.4f} bits/sym  (identical for both modes)",
        fontsize=12,
    )

    # ── (0,0): raw-delta storage — uint16, full range ─────────────────────────
    ax = axes[0, 0]
    # Bucket the full [0, 65535] range into 128 bins to show both lobes
    bins_full = np.linspace(0, 65536, 129)
    bar_histogram(ax, raw_u16, bins=bins_full, color=blue)
    ax.set_title(
        f"Mode 1: raw delta  (zigzag=false) — storage view\n"
        f"uint16 codes across [0, {bklen_raw - 1}]  |  bklen required: {bklen_raw:,}",
        fontsize=10,
    )
    ax.set_xlabel("uint16 code value")
    ax.set_ylabel("Count")
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    annotate_box(
        ax,
        f"Positive deltas → [0, {radius - 1}]\n"
        f"Negative deltas → [{bklen_raw - radius + 1:,}, {bklen_raw - 1:,}]\n"
        f"Gap [{radius}, {bklen_raw - radius:,}] is empty\n"
        f"PHF must allocate {bklen_raw:,}-entry codebook",
        color="lightyellow",
    )

    # ── (0,1): zigzag storage — uint16, [0, bklen_zig] ───────────────────────
    ax = axes[0, 1]
    bins_zig = np.arange(-0.5, bklen_zig + 0.5)
    bar_histogram(ax, zig_u16, bins=bins_zig, color=green)
    ax.set_title(
        f"Mode 2: zigzag  (zigzag=true) — storage view\n"
        f"uint16 codes in [0, {bklen_zig - 2}]  |  bklen required: {bklen_zig}",
        fontsize=10,
    )
    ax.set_xlabel("uint16 code value  (0 = zero-delta, even = +k, odd = -k)")
    ax.set_ylabel("Count")
    annotate_box(
        ax,
        f"All codes contiguous in [0, {bklen_zig - 2}]\n"
        f"PHF codebook: only {bklen_zig} entries\n"
        f"({bklen_raw // bklen_zig}× smaller than raw-delta)",
        color="palegreen",
        xy=(0.98, 0.97), ha="right",
    )

    # ── (1,0): raw-delta — signed delta domain ────────────────────────────────
    ax = axes[1, 0]
    bins_s = np.arange(-xlim - 0.5, xlim + 1.5)
    mask_raw = (raw_signed >= -xlim) & (raw_signed <= xlim)
    bar_histogram(ax, raw_signed[mask_raw], bins=bins_s, color=blue)
    ax.set_title(
        f"Mode 1: raw delta — delta domain (int16 reinterpretation)\n"
        f"Shown: ±{xlim} window  ({100 * mask_raw.mean():.1f}% of codes)",
        fontsize=10,
    )
    ax.set_xlabel("Signed delta value")
    ax.set_ylabel("Count")
    ax.xaxis.set_major_locator(mticker.MultipleLocator(max(1, xlim // 5)))
    outlier_frac = 100.0 * (raw_signed == 0).sum() / n   # zero-code fraction
    annotate_box(ax, f"Zero-code fraction: {outlier_frac:.2f}%\n(perfect predictions)")

    # ── (1,1): zigzag — decoded signed delta domain ───────────────────────────
    ax = axes[1, 1]
    mask_zig = (zig_signed >= -xlim) & (zig_signed <= xlim)
    bar_histogram(ax, zig_signed[mask_zig], bins=bins_s, color=green)
    ax.set_title(
        f"Mode 2: zigzag — delta domain (zigzag decoded)\n"
        f"Shown: ±{xlim} window  ({100 * mask_zig.mean():.1f}% of codes)",
        fontsize=10,
    )
    ax.set_xlabel("Signed delta value")
    ax.set_ylabel("Count")
    ax.xaxis.set_major_locator(mticker.MultipleLocator(max(1, xlim // 5)))
    annotate_box(
        ax,
        "Delta distributions are identical.\nBoth modes encode the same deltas;\n"
        "only the uint16 storage layout differs.",
        xy=(0.98, 0.97), ha="right", color="palegreen",
    )

    # Sync y-axes in the bottom row so the bell shapes are directly comparable
    ymax = max(axes[1, 0].get_ylim()[1], axes[1, 1].get_ylim()[1])
    axes[1, 0].set_ylim(0, ymax)
    axes[1, 1].set_ylim(0, ymax)

    plt.tight_layout()

    if args.out:
        plt.savefig(args.out, dpi=150, bbox_inches="tight")
        print(f"Saved: {args.out}")
    if not args.no_show and not args.out:
        plt.show()
    elif args.out and not args.no_show:
        plt.show()


if __name__ == "__main__":
    main()
