#!/usr/bin/env bash
# Regenerate every baseline patch in artifact/patches/ from upstream sources.
#
# Run this to verify PROVENANCE.md still matches reality, or to rebuild the
# patches after touching a baseline tree. It is the check that keeps the
# provenance honest: if a patch changes, a baseline moved and PROVENANCE.md
# needs updating.
#
#   ./artifact/capture_provenance.sh [--check]
#
# --check  regenerate into a temp dir and diff against the committed patches;
#          exits non-zero if they differ. Use in CI or before tagging.

set -euo pipefail

COMPRESSORS="${COMPRESSORS_DIR:-$HOME/compressors}"
ARTIFACT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

if [[ $CHECK -eq 1 ]]; then
    OUT="$(mktemp -d)"
    trap 'rm -rf "$OUT"' EXIT
else
    OUT="$ARTIFACT/patches"
fi
mkdir -p "$OUT/cuszp" "$OUT/baselines"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# .yuxi_notes holds a third party's raw agent-session transcripts (see
# PROVENANCE.md "Attribution"). Never ship them: they carry an outside
# collaborator's email, org name, and cluster paths.
EXCL=(--exclude=build --exclude=build_sm90 --exclude=.DS_Store --exclude=.git
      --exclude=.yuxi_notes)

# ── cuSZp: no git history locally, so patches are reconstructed against the
#    upstream release tags fetched fresh from GitHub. ────────────────────────
echo "==> fetching upstream cuSZp"
git clone -q https://github.com/szcompressor/cuSZp.git "$WORK/upstream"

# Normalize the file headers so patches are byte-stable across runs and
# machines: strip the --exclude flags diff echoes back at us, and rewrite the
# absolute from/to directories to a/ and b/. Without this, the temp checkout
# path and $HOME land in every header and --check reports spurious drift.
gen() {  # gen <from-dir> <to-dir> <out-file>
    diff -ruN "${EXCL[@]}" "$1" "$2" 2>/dev/null \
        | sed -e "s/ '--exclude=[^']*'//g" \
              -e "s|$1/|a/|g" \
              -e "s|$2/|b/|g" > "$3" || true
}

for tag in cuSZp-V2.0.1 cuSZp-V3.0.0; do
    v="${tag#cuSZp-V}"
    ( cd "$WORK/upstream" && git archive --format=tar --prefix="$tag/" "$tag" ) \
        | tar xf - -C "$WORK"
    echo "==> cuSZp $v: upstream $tag -> local base"
    gen "$WORK/$tag" "$COMPRESSORS/$tag" "$OUT/cuszp/v${v}_upstream-to-base.patch"
    for variant in optimized split; do
        [[ -d "$COMPRESSORS/${tag}_${variant}" ]] || continue
        echo "==> cuSZp $v: base -> $variant"
        gen "$COMPRESSORS/$tag" "$COMPRESSORS/${tag}_${variant}" \
            "$OUT/cuszp/v${v}_base-to-${variant}.patch"
    done
done

# ── git-tracked baselines: record uncommitted local modifications. ──────────
for d in cuSZ cuSZ-Hi FZ-GPU PFPL lsCOMP MANS MGARD SPERR tthresh SZ3 FSZ zfp; do
    [[ -d "$COMPRESSORS/$d/.git" ]] || continue
    if [[ -n "$(git -C "$COMPRESSORS/$d" status --porcelain | grep '^ M' || true)" ]]; then
        echo "==> $d: local modifications"
        git -C "$COMPRESSORS/$d" diff > "$OUT/baselines/${d}_local.patch"
    fi
done

# ── manifest: URL, commit, tag, and dirty state for every baseline. ─────────
{
    echo "# Baseline manifest — regenerated by capture_provenance.sh"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo
    printf "%-10s %-46s %-42s %-22s %s\n" NAME URL COMMIT TAG DIRTY
    for d in "$COMPRESSORS"/*/; do
        n="$(basename "$d")"
        if [[ -d "$d/.git" ]]; then
            printf "%-10s %-46s %-42s %-22s %s\n" "$n" \
                "$(git -C "$d" config --get remote.origin.url || echo -)" \
                "$(git -C "$d" rev-parse HEAD)" \
                "$(git -C "$d" describe --tags --always 2>/dev/null || echo -)" \
                "$(git -C "$d" status --porcelain | grep -c '^ M' || true) modified"
        else
            printf "%-10s %-46s %-42s %-22s %s\n" "$n" "(no git — see PROVENANCE.md)" - - -
        fi
    done
} > "$OUT/MANIFEST.txt"

if [[ $CHECK -eq 1 ]]; then
    # MANIFEST embeds a timestamp, so compare patches only.
    if diff -r -x MANIFEST.txt "$OUT" "$ARTIFACT/patches" > /dev/null 2>&1; then
        echo "OK: committed patches match regenerated ones."
    else
        echo "DRIFT: committed patches differ from regenerated. Details:"
        diff -r -x MANIFEST.txt "$OUT" "$ARTIFACT/patches" || true
        exit 1
    fi
else
    echo "Wrote patches to $OUT"
fi
